### ISSUE TITLE
Timestamp bug

### ISSUE THREAD

**Issue by andresti** [cmsdtoffline/DTDPGAnalysis#23]
I was trying to read the timestamp information from the DTTrees while I discovered it doesn't match with any timestamp format I could find.

It seems to me that the timestamp information is inadvertently converted from unsigned long long to float in the script:
https://github.com/cmsdtoffline/DTDPGAnalysis/blob/master/src/TTreeGenerator.cc#L317
Variable definition here: https://github.com/cmsdtoffline/DTDPGAnalysis/blob/master/interface/DefineTreeVariables.h#L10

The return from EventAuxiliary is like this:
https://github.com/cms-sw/cmssw/blob/master/DataFormats/Provenance/interface/EventAuxiliary.h#L62
and the timestampt itself is defined here:
https://github.com/cms-sw/cmssw/blob/master/DataFormats/Provenance/interface/Timestamp.h#L28

**Comment by battibass** [comment]
@andresti : thanks for reporting this, we will fix it toghether with some other changes that we plan to make in these days.

**Comment by battibass** [comment]
I moved the timestamp format in the ntuples to unsigned long long as part of [this PR](https://github.com/cmsdtoffline/DTDPGAnalysis/pull/24/)
